# Generated by Django 5.0.7 on 2024-10-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background_slider_images',
            options={'ordering': ['order'], 'verbose_name': 'background_slider_images', 'verbose_name_plural': 'background_slider_images'},
        ),
    ]
