# Generated by Django 5.0.7 on 2024-10-19 11:56

import Digital_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0002_alter_background_slider_images_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('book', 'Book'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('product_file', models.FileField(upload_to=Digital_shop.models.upload_to_based_on_type)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
