# Generated by Django 5.0.7 on 2024-10-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
