# Generated by Django 5.0.7 on 2024-10-19 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0006_products_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='products',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
