# Generated by Django 5.0.7 on 2024-11-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0012_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background_slider_images',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='background_slider_images',
            name='paragraph',
        ),
    ]
