# Generated by Django 5.0.7 on 2024-11-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0013_remove_background_slider_images_heading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background_slider_images',
            options={'ordering': ['order'], 'verbose_name': 'Background Slider Image', 'verbose_name_plural': 'Background Slider Images'},
        ),
    ]
