# Generated by Django 5.0.7 on 2024-11-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0015_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
        migrations.AddField(
            model_name='membership',
            name='level_1_price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='level_2_price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
