# Generated by Django 5.0.7 on 2024-11-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0016_remove_membership_price_membership_level_1_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='training_duration',
        ),
    ]
