# Generated by Django 5.0.7 on 2024-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0018_usermembershiplevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembershiplevel',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usermembershiplevel',
            name='membership',
            field=models.CharField(max_length=255),
        ),
    ]
