# Generated by Django 5.0.7 on 2024-12-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0020_usermembershiplevel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='membershipVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/')),
                ('level', models.CharField(choices=[('OGS501', 'Level 1 - OGS501'), ('OGS502', 'Level 2 - OGS502'), ('LS501', 'Level 1 - LS501'), ('LS502', 'Level 2 - LS502'), ('PM501', 'Level 1 - PM501'), ('PM502', 'Level 2 - PM502')], max_length=300)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Digital_shop.membership')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
