# Generated by Django 5.0.7 on 2024-12-07 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_shop', '0022_uservideoprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together={('user', 'video')},
        ),
    ]
